---

- include_role: 
    name: cloudera_api

- name: setup the json message and see if it looks right
  set_fact:
    cmca_message: "{{ lookup('template', 'Cmca.j2') | to_nice_json }}"

- name: Fix up the json
  template:
    src: Cmca.j2
    dest: /tmp/cmca_json.json
    owner: cloudera-scm
    group: cloudera-scm
    mode: '0755'

- name: fetch file to the ansible machine to make uri work
  fetch:
    src: /tmp/cmca_json.json
    dest: tmp/cmca_json.json
    flat: yes

#- name: Debug the Cmca file
#  debug:
#    var: cmca_message
#    verbosity: 1

#- name: submit the request - using curl cause it's easier
#  command: "curl -i -v -uadmin:admin -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '@/opt/cmca_request.json' '{{ cm_api_url }}/cm/commands/generateCmca'"

#https://archive.cloudera.com/cm7/7.1.3/generic/jar/cm_api/apidocs/json_ApiGenerateCmcaArguments.html
- name: submit the auto-tls request
  uri:
    url: "{{ cm_api_url }}/cm/commands/generateCmca"
    method: POST
    body_format: json
    body: "{{ lookup('file', 'tmp/cmca_json.json') }}"
    status_code: 200
    force_basic_auth: yes
    user: "{{ scm_default_user }}"
    password: "{{ scm_default_pass }}"
    return_content: yes
  register: ca_resp
  tags: send_request

- debug:
    var: ca_resp
    verbosity: 1
  tags: send_request

- set_fact:
    command_id: "{{ ca_resp.json.id }}"
  tags: send_request

- debug:
    msg: "Login to Cloudera Manager to monitor import progress - http://{{ groups['manager'][0] }}:{{ scm_port }}/cmf/command/{{ command_id }}/details"
    verbosity: 1
  tags: send_request
    
- name: Wait for import cluster template command to complete
  uri: 
    url: "{{ cm_api_url }}/commands/{{ command_id }}"
    body_format: json
    force_basic_auth: yes
    user: "{{ scm_default_user }}"
    password: "{{ scm_default_pass }}"
    return_content: yes
  register: result
  until: not result.json.active
  retries: 10
  delay: 60
  failed_when: "'Failed to enable Auto-TLS' in result.content"
  tags: send_request

  