cluster_version: 7.1.3
cluster_name: cdp-cfm

hdfs_is_ha: false

cluster_services:

  - type: nifi

  - type: nifiregistry

host_templates:
  - name: HostTemplate-Master1
    cardinality: 1
    roles:
    - "NIFIREGISTRY-1-NIFI_REGISTRY_SERVER-BASE"
    - "ZOOKEEPER-1-SERVER-BASE"

  - name: HostTemplate-Worker
    cardinality: "{{ groups['worker'] | length }}"
    roles:
    - "NIFI-1-NIFI_NODE-BASE"