---

- hosts: manager
  become: yes

  tasks:
  - name: merge the main parcel in with the other component ones
    set_fact:
      parcel_list: "{{ scm_parcel_repositories + main_parcel }}"

  - name: debug merge
    debug: var=parcel_list

  - name: get the manifest files
    include_tasks: process_parcel_repo.yml
    with_flattened: 
      - "{{ parcel_list }}"
    loop_control:
      loop_var: parcel_path