---
    
  - name: setup Chrony
    lineinfile:
      path: /etc/chrony.conf
      line: server 169.254.169.123 prefer iburst minpoll 4 maxpoll 4
    
  - name: reset chrony
    systemd:
      name: chronyd
      state: restarted
      
  - name: set timezone to local
    shell: timedatectl set-timezone {{ timezone }}
