cluster_version: 7.1.3
cluster_name: cdp-base

cluster_services:

  - type: hdfs
    dfs_data_dir_list: /dfs/dn
    fs_checkpoint_dir_list: /dfs/snn
    dfs_name_dir_list: /dfs/nn
    dfs_journalnode_edits_dir: /dfs/jn

  - type: spark

  - type: yarn
    yarn_nodemanager_local_dirs: /tmp/nm
    yarn_nodemanager_log_dirs: /var/log/nm

  - type: zookeeper

host_templates:
  - name: HostTemplate-Master1
    cardinality: 1
    roles:
    - HDFS-1-NAMENODE-BASE
    - HDFS-1-FAILOVERCONTROLLER-BASE
    - HDFS-1-JOURNALNODE-BASE
    - YARN-1-RESOURCEMANAGER-BASE
    - ZOOKEEPER-1-SERVER-BASE
  - name: HostTemplate-Master2
    cardinality: 1
    roles:
    - HDFS-1-NAMENODE-BASE
    - HDFS-1-FAILOVERCONTROLLER-BASE
    - HDFS-1-JOURNALNODE-BASE
    - YARN-1-RESOURCEMANAGER-BASE
    - ZOOKEEPER-1-SERVER-BASE
  - name: HostTemplate-Master3
    cardinality: 1
    roles:
    - HDFS-1-BALANCER-BASE
    - HDFS-1-JOURNALNODE-BASE
    - YARN-1-JOBHISTORY-BASE
    - ZOOKEEPER-1-SERVER-BASE
    - SPARK_ON_YARN-1-SPARK_YARN_HISTORY_SERVER-BASE
  - name: HostTemplate-Worker
    cardinality: 3
    roles:
    - HDFS-1-DATANODE-BASE
    - YARN-1-NODEMANAGER-BASE
    - SPARK_ON_YARN-1-GATEWAY-BASE