---
- name: Install the Cloudera Manager Server Packages
  yum:
    name:
    - cloudera-manager-daemons
    - cloudera-manager-server
    - cloudera-manager-agent
    - openldap-clients
    state: installed

- name: Prepare Cloudera Manager Server External Database
  command: |
    {{ scm_prepare_database_script_path }}  -f
    --host {{ groups['database'][0] }}
    {{ database_type }} {{ databases.scm.name }} {{ databases.scm.user }} {{ databases.scm.pass }}

- name: Create CSD directory
  file:
    path: /opt/cloudera/csd
    state: directory
    owner: cloudera-scm
    group: cloudera-scm
    mode: 0755
  
- name: Download CSDs
  get_url:
    url: "{{ item }}"
    dest: /opt/cloudera/csd
    mode: 0644
  with_items: "{{ scm_csds }}"
  when: scm_csds is defined

- name: Start the Cloudera Manager Server
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  notify:
    - wait cloudera-scm-server
  with_items:
    - cloudera-scm-server
    - cloudera-scm-agent

# Trigger handler to wait for SCM to startup
- meta: flush_handlers

- include_role:
    name: cloudera_api

- debug:
    var: cm_api_url
    verbosity: 1
  
- include: license.yml
- include: scm.yml