---

- include_vars: "clusters/{{ cluster_def }}/vars/cluster-vars.yml"

- include_role: 
    name: cloudera_api

- include_role:
    name: cm_gethosts
        
- name: Print the extracted host identifiers and names
  debug:
    var: scm_hosts
    verbosity: 1

- name: Discover product versions from parcel manifests
  uri:
    url: "{{ item }}/manifest.json"
    status_code: 200
    body_format: json
    return_content: yes
  register: manifests
  with_items: 
    - "{{ scm_parcel_repositories }}"
  
- set_fact:
    scm_product_list: "{{ manifests.results | map(attribute='json') | list | json_query('[*].parcels[*].parcelName') | list | sum(start=[]) }}"

- set_fact:
    scm_products: "{{ scm_product_list | map('regex_replace', '-[a-z0-9]+.parcel$','') | list | unique  }}"  
    
- name: generate host config
  set_fact: 
    cluster_template_json: "{{ lookup('template', 'base.j2', convert_date=False) }}"

- debug:
    var: cluster_template_json
    verbosity: 1

- debug: # debug hdfs ha
    var: hdfs_is_ha
    verbosity: 1

- debug:
    var: "{{ cluster_template_json | to_nice_json }}"

#- name: debug write template
#  local_action:
#    module: copy
#    content: "{{ cluster_template_json }}"
#    dest: "tmp/template-{{ cluster_name }}.json"
#    owner: brian
#    group: brian
#    mode: 777

- include: apply_template.yml
#- name: count host templates