cluster_cm_version: 7.2.6
cluster_version: 7.1.5.9
cluster_def: cdp-cdsw-expanded

# cloud flags
aws: true

# switch to openjdk lets see if this fixes impala?
java_repo: java-1.8.0-openjdk-devel
java_type: openjdk # cldr_java 
java_path: /usr/lib/jvm 
#java_path: /usr/java/jdk1.8.0_232-cloudera 
#cldr_java_repo: "https://{{ cloudera_key }}@archive.cloudera.com/p/cm7/{{ cluster_cm_version }}/redhat7/yum/RPMS/x86_64/openjdk8-8.0+232_9-cloudera.x86_64.rpm"

scm_repo_url: "https://{{ cloudera_key }}@archive.cloudera.com/p/cm7/{{ cluster_cm_version }}/redhat7/yum/"
scm_repo_gpgkey: "https://{{ cloudera_key }}@archive.cloudera.com/p/cm7/{{ cluster_cm_version }}/redhat7/yum/RPM-GPG-KEY-cloudera"

cdsw_version: 1.9.1

scm_csds:
  - "https://{{ cloudera_key }}@archive.cloudera.com/p/CFM/2.x/redhat7/yum/tars/parcel/NIFI-1.11.4.2.0.4.0-80.jar"
  - "https://{{ cloudera_key }}@archive.cloudera.com/p/CFM/2.x/redhat7/yum/tars/parcel/NIFIREGISTRY-0.6.0.2.0.4.0-80.jar"
  - "https://{{ cloudera_key }}@archive.cloudera.com/p/cdsw1/{{ cdsw_version }}/csd/CLOUDERA_DATA_SCIENCE_WORKBENCH-CDPDC-1.9.1.jar"
  - "https://{{ cloudera_key }}@archive.cloudera.com/p/csa/1.2.1.0/csd/FLINK-1.10.0-csa1.2.1.0-cdh7.2.1.0-327-7398223.jar"
  - "https://{{ cloudera_key }}@archive.cloudera.com/p/spark3/3.0.7110.0/csd/LIVY_FOR_SPARK3-0.6.0.3.0.7110.0-81.jar"
  - "https://{{ cloudera_key }}@archive.cloudera.com/p/spark3/3.0.7110.0/csd/SPARK3_ON_YARN-3.0.1.3.0.7110.0-81.jar"
  
scm_parcel_repositories:
  - "https://{{ cloudera_key }}@archive.cloudera.com/p/CFM/2.x/redhat7/yum/tars/parcel/"
  - "https://{{ cloudera_key }}@archive.cloudera.com/p/cdsw1/{{ cdsw_version }}/parcels/"
  - "https://{{ cloudera_key }}@archive.cloudera.com/p/csa/1.2.1.0/parcels/"
  - "https://{{ cloudera_key }}@archive.cloudera.com/p/spark3/3.0.7110.0/parcels/"
  - "https://repo.anaconda.com/pkgs/misc/parcels"
  - "https://{{ cloudera_key }}@archive.cloudera.com/p/cdh7/{{ cluster_version }}/parcels/"

scm_prepare_database_script_path: "/opt/cloudera/cm/schema/scm_prepare_database.sh"
database_type: "postgresql"
scm_port: 7180

scm_default_user: admin
# the install isn't updating the default...
scm_default_pass: admin
#scm_default_pass: briza1!

kdc_admin: admin
kdc_enc: aes256-cts

# ldap setup
ldap_protocol: ldaps://
ldap_bind_pass: cmBindPass1

# knox setup
knox_master_secret: knoxMasterSecret
idbroker_master_secret: idBrokerMasterSecret

scm_license_file: ../../../../secrets/bl_demo_2020_2021_cloudera_license.txt
