scm_repo_url: "https://{{ cloudera_key }}@archive.cloudera.com/p/cm7/7.1.3/redhat7/yum/"
scm_repo_gpgkey: "https://{{ cloudera_key }}@archive.cloudera.com/p/cm7/7.1.3/redhat7/yum/RPM-GPG-KEY-cloudera"
cldr_java_repo: "https://{{ cloudera_key }}@archive.cloudera.com/p/cm7/7.1.3/redhat7/yum/RPMS/x86_64/openjdk8-8.0+232_9-cloudera.x86_64.rpm"

scm_prepare_database_script_path: "/opt/cloudera/cm/schema/scm_prepare_database.sh"
database_type: "postgresql"