cluster_version: 7.1.4
cluster_name: cdp-cdsw-expanded

hdfs_is_ha: true
atlas_enabled: true
ranger_enabled: true
knox_enabled: true
idbroker: false

# domain has to have the public ip..
#CDSW_DOMAIN: cdsw.${PUBLIC_IP}.nip.io
# we really need to automate this step...
# note this needs editing will currently fail
CDSW_IP: {{ hostvars[groups['cdsw_master'][0]] }}
# we coded this in from the ec2.tf settings ebs_docker_att
# It appeared in our system as: /dev/nvme1n1 ....
# what we set: /dev/sdf
# second drive will always appear as nvme1
# see: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html
DOCKER_DEVICE: /dev/nvme1n1

cluster_services:

  - type: atlas

  - type: cdsw

  - type: ranger
    ranger_pass: rangerPass1

  - type: hbase

  - type: hdfs
    dfs_data_dir_list: /dfs/dn
    fs_checkpoint_dir_list: /dfs/snn
    dfs_name_dir_list: /dfs/nn
    dfs_journalnode_edits_dir: /dfs/jn

  - type: hive

  - type: hive_on_tez

  - type: hue

  - type: impala

  - type: kafka

  - type: knox
    gateway_secret: knoxPass1
    idbroker_secret: idbrokerPass1

  - type: flink

  - type: oozie

  - type: solr

  - type: spark
  - type: spark3

  - type: yarn
    yarn_nodemanager_local_dirs: /tmp/nm
    yarn_nodemanager_log_dirs: /var/log/nm

  - type: yarn_queuemanager

  - type: zookeeper

host_templates:
  - name: HostTemplate-Master1
    cardinality: 1
    roles:
    - "HBASE-1-MASTER-BASE"
    - "HDFS-1-NAMENODE-BASE"
    - "HDFS-1-JOURNALNODE-BASE"
    - "HDFS-1-FAILOVERCONTROLLER-BASE"
    - "IMPALA-1-STATESTORE-BASE"
    - "IMPALA-1-CATALOGSERVER-BASE"
    - "YARN-1-RESOURCEMANAGER-BASE"
    - "QUEUEMANAGER-1-QUEUEMANAGER_WEBAPP-BASE"
    - "QUEUEMANAGER-1-QUEUEMANAGER_STORE-BASE"
    - "ZOOKEEPER-1-SERVER-BASE"
  - name: HostTemplate-Master2
    cardinality: 1
    roles:
    - "HBASE-1-MASTER-BASE"
    - "HDFS-1-NAMENODE-BASE"
    - "HDFS-1-JOURNALNODE-BASE"
    - "HDFS-1-FAILOVERCONTROLLER-BASE"
    - "HIVE_ON_TEZ-1-HIVESERVER2-BASE"
    - "HIVE_ON_TEZ-1-GATEWAY-BASE"
    - "SPARK3_ON_YARN-1-GATEWAY-BASE"
    - "SPARK_ON_YARN-1-GATEWAY-BASE"
    - "YARN-1-RESOURCEMANAGER-BASE"
    - "YARN-1-GATEWAY-BASE"
    - "ZOOKEEPER-1-SERVER-BASE"
  - name: HostTemplate-Master3
    cardinality: 1
    roles:
    - "atlas-ATLAS_SERVER-BASE"
    - "ranger-RANGER_USERSYNC-BASE"
    - "ranger-RANGER_TAGSYNC-BASE"
    - "ranger-RANGER_ADMIN-BASE"
    - "HBASE-1-MASTER-BASE"
    - "HDFS-1-BALANCER-BASE"
    - "HDFS-1-JOURNALNODE-BASE"
    - "HIVE-1-HIVEMETASTORE-BASE"
    - "INFRA_SOLR-SOLR_SERVER-BASE"
    - "YARN-1-JOBHISTORY-BASE"
    - "ZOOKEEPER-1-SERVER-BASE"
    - "SPARK_ON_YARN-1-SPARK_YARN_HISTORY_SERVER-BASE"
    - "SPARK3_ON_YARN-1-SPARK_YARN_HISTORY_SERVER-BASE"
  - name: HostTemplate-Worker
    cardinality: "{{ groups['worker'] | length }}"
    roles:
    - "HBASE-1-REGIONSERVER-BASE"
    - "HDFS-1-DATANODE-BASE"
    - "KAFKA-1-BROKER-BASE"
    - "YARN-1-NODEMANAGER-BASE"
    - "SPARK_ON_YARN-1-GATEWAY-BASE"
    - "SPARK3_ON_YARN-1-GATEWAY-BASE"
    - "HIVE_ON_TEZ-1-GATEWAY-BASE"
    - "IMPALA-1-IMPALAD-BASE"
    - "FLINK-1-GATEWAY-BASE"
  - name: HostTemplate-Edge
    cardinality: 1
    roles:
    - "HDFS-1-HTTPFS-BASE"
    - "HBASE-1-HBASERESTSERVER-BASE"
    - "HBASE-1-HBASETHRIFTSERVER-BASE"
    - "HUE-1-HUE_SERVER-BASE"
    - "HUE-1-HUE_LOAD_BALANCER-BASE"
    - "HUE-1-KT_RENEWER-BASE"
    - "KNOX-1-KNOX_GATEWAY-BASE"
    - "KNOX-1-GATEWAY-BASE"
    - "OOZIE-1-OOZIE_SERVER-BASE"
    - "SPARK_ON_YARN-1-GATEWAY-BASE"
    - "SPARK3_ON_YARN-1-GATEWAY-BASE"
    - "HIVE-1-GATEWAY-BASE"
    - "HIVE_ON_TEZ-1-GATEWAY-BASE"
    - "FLINK-1-GATEWAY-BASE"
    - "FLINK-1-FLINK_HISTORY_SERVER-BASE"

  - name: HostTemplate-CDSWMaster
    cardinality: 1
    roles:
    - "CDSW-1-CDSW_APPLICATION-BASE"
    - "CDSW-1-CDSW_DOCKER-BASE"
    - "CDSW-1-CDSW_MASTER-BASE"
    - "HDFS-1-GATEWAY-BASE"
    - "HIVE-1-GATEWAY-BASE"
    - "HIVE_ON_TEZ-1-GATEWAY-BASE"
    - "FLINK-1-GATEWAY-BASE"
    - "SPARK_ON_YARN-1-GATEWAY-BASE"
    - "SPARK3_ON_YARN-1-GATEWAY-BASE"
    