---
- hosts: all
  become: yes
  vars_files:
    - vars/cm_config.yml
  
  tasks:
  
  - name: setup ntp
    include_role:
      name: common
  
  - name: add epel dependency
    include_role:
      name: epel
  
  - name: add cloudera repo
    include_role:
      name: cm-repo
    
  - name: add java
    include_role:
      name: java
    
  - name: add db_access
    include_role:
      name: db_driver
    
  - name: run prereqs
    include_role:
      name: cdp_preinstall
  
  - name: Install Cloudera Manager Agents
    yum:
      name:
      - cloudera-manager-daemons
      - cloudera-manager-agent
      update_cache: yes
      state: installed

  - name: create parcel dirs
    file:
      path: "{{ item }}" 
      state: directory
      owner: cloudera-scm
      group: cloudera-scm
      mode: '0755'
    loop:
      - "/opt/cloudera/parcel-repo"
      - "/opt/cloudera/parcels"
      - "/opt/cloudera/parcel-cache"

  - name: get parcels / and sha 
    get_url:
      url: https://{{ cloudera_key }}@archive.cloudera.com/p/cdh7/7.1.3.0/parcels/{{ item }}
      dest: /opt/cloudera/parcel-repo/{{ item }}
    loop:
      - "CDH-7.1.3-1.cdh7.1.3.p0.4992530-el7.parcel"
      - "CDH-7.1.3-1.cdh7.1.3.p0.4992530-el7.parcel.sha1"

  - name: extract parcels
    unarchive:
      src: /opt/cloudera/parcel-repo/CDH-7.1.3-1.cdh7.1.3.p0.4992530-el7.parcel
      dest: /opt/cloudera/parcels/
      remote_src: yes

  - name: symlink the parcel dir
    file:
      src: /opt/cloudera/parcels/CDH-7.1.3-1.cdh7.1.3.p0.4992530
      dest: /opt/cloudera/parcels/CDH
      state: link

  - name: create don't delete
    file:
      path: /opt/cloudera/parcels/CDH/.dont_delete
      state: touch
      owner: cloudera-scm
      group: cloudera-scm

  - name: bulk chown
    file:
      path: /opt/cloudera
      state: directory
      recurse: yes
      owner: cloudera-scm
      group: cloudera-scm
      mode: '0755'
