---
- hosts: all
  become: yes
  vars_files:
    - vars/cm_config.yml
  
  tasks:
  
  - name: setup ntp
    include_role:
      name: common
  
  - name: add epel dependency
    include_role:
      name: epel
  
  - name: add cloudera repo
    include_role:
      name: cm-repo
    
  - name: add java
    include_role:
      name: java
    
  - name: add db_access
    include_role:
      name: db_driver
    
  - name: run prereqs
    include_role:
      name: cdp_preinstall
  
  - name: Install Cloudera Manager Agents
    yum:
      name:
      - cloudera-manager-daemons
      - cloudera-manager-agent
      update_cache: yes
      state: installed

  - name: create parcel dirs
    file:
      path: "{{ item }}" 
      state: directory
      owner: cloudera-scm
      group: cloudera-scm
      mode: '0755'
    loop:
      - "/opt/cloudera/csd"
      - "/opt/cloudera/parcel-repo"
      - "/opt/cloudera/parcels"
      - "/opt/cloudera/parcel-cache"
    tags:
      - preload_parcels

  - name: Download CSDs
    get_url:
      url: "{{ item }}"
      dest: /opt/cloudera/csd
      mode: 0644
    with_items: "{{ scm_csds }}"
    when: scm_csds is defined
    tags:
      - preload_parcels

  - name: install transmission
    yum:
      name: transmission
      state: present
    tags:
      - preload_parcels

  - name: get the manifest files
    include_tasks: playbooks/process_parcel_repo.yml
    with_flattened: 
      - "{{ scm_parcel_repositories }}"
    loop_control:
      loop_var: parcel_path
    tags:
      - preload_parcels
# CDH 2755
# link 0777
  #- name: chown parcels
  ##  file:
   #   path: /opt/cloudera/parcels
   #   state: directory
   #   recurse: yes
   #   owner: cloudera-scm
   #   group: cloudera-scm
   #   mode: '0755'
   # tags:
   #   - preload_parcels
# folder 755
# contents 640  
  #- name: chown parcel-repo
  #  file:
  #    path: /opt/cloudera/parcel-repo
  #    state: directory
  #    recurse: yes
  #    owner: cloudera-scm
  #    group: cloudera-scm
  #    mode: '0755'
  #  tags:
  #    - preload_parcels
  
