---
- hosts: all
  become: yes
  vars_files:
    - vars/cm_config.yml
  
  tasks:
  
  - name: setup ntp
    include_role:
      name: common
  
  - name: add epel dependency
    include_role:
      name: epel
  
  - name: add cloudera repo
    include_role:
      name: cm-repo
    
  - name: add java
    include_role:
      name: java
    
  - name: add db_access
    include_role:
      name: db_driver
    
  - name: run prereqs
    include_role:
      name: cdp_preinstall
  
  - name: Install Cloudera Manager Agents
    yum:
      name:
      - cloudera-manager-daemons
      - cloudera-manager-agent
      update_cache: yes
      state: installed

  - name: create parcel dirs
    file:
      path: "{{ item }}" 
      state: directory
      owner: cloudera-scm
      group: cloudera-scm
      mode: '0740'
    loop:
      - "/opt/cloudera/csd"
      - "/opt/cloudera/parcel-repo"
      - "/opt/cloudera/parcels"
      - "/opt/cloudera/parcel-cache"

  - name: Download CSDs
    get_url:
      url: "{{ item }}"
      dest: /opt/cloudera/csd
      mode: 0644
    with_items: "{{ scm_csds }}"
    when: scm_csds is defined

  - name: merge the main parcel in with the other component ones
    set_fact:
      parcel_list: "{{ scm_parcel_repositories + main_parcel }}"

  - name: get the manifest files
    include_tasks: playbooks/process_parcel_repo.yml
    with_flattened: 
      - "{{ parcel_list }}"
    loop_control:
      loop_var: parcel_path

  - name: bulk chown
    file:
      path: /opt/cloudera
      state: directory
      recurse: yes
      owner: cloudera-scm
      group: cloudera-scm
      mode: '0740'
