---
- hosts: all
  become: yes
  vars_files:
    - vars/cm_config.yml
  
  tasks:
  
  - name: setup ntp
    include_role:
      name: common
  
  - name: add epel dependency
    include_role:
      name: epel
  
  - name: add cloudera repo
    include_role:
      name: cm-repo
    
  - name: add java
    include_role:
      name: java
    
  - name: add db_access
    include_role:
      name: db_driver
    
  - name: run prereqs
    include_role:
      name: cdp_preinstall
  
  - name: Install Cloudera Manager Agents
    yum:
      name:
      - cloudera-manager-daemons
      - cloudera-manager-agent
      update_cache: yes
      state: installed

  - name: create parcel dirs
    file:
      path: "{{ item }}" 
      state: directory
      owner: cloudera-scm
      group: cloudera-scm
      mode: '0740'
    loop:
      - "/opt/cloudera/csd"
      - "/opt/cloudera/parcel-repo"
      - "/opt/cloudera/parcels"
      - "/opt/cloudera/parcel-cache"

  - name: Download CSDs
    get_url:
      url: "{{ item }}"
      dest: /opt/cloudera/csd
      mode: 0644
    with_items: "{{ scm_csds }}"
    when: scm_csds is defined

# need to make this into some sort of role that reads from a list in future
  - name: get the manifest file
    get_url:
      url: https://{{ cloudera_key }}@archive.cloudera.com/p/cdh7/7.1.3.0/parcels/manifest.json
      dest: /tmp/manifest.json

  - name: extract manifest
    shell: cat /tmp/manifest.json
    register: result

  - name: set the facts
    set_fact:
      parcel_manifest: "{{ result.stdout | from_json }}"
   
  - name: write out shas
    copy:
      content: "{{ item.hash }}"
      dest: "/opt/cloudera/parcel-repo/{{ item.parcelName }}.sha"
      owner: cloudera-scm
      group: cloudera-scm
      mode: '0740'
    with_items: "{{ parcel_manifest.parcels }}"
    when: item.parcelName.endswith('el7.parcel')

  - name: get parcels  
    get_url:
      url: "https://{{ cloudera_key }}@archive.cloudera.com/p/cdh7/7.1.3.0/parcels/{{ item.parcelName }}"
      dest: "/opt/cloudera/parcel-repo/{{ item.parcelName }}"
      owner: cloudera-scm
      group: cloudera-scm
      mode: '0740'
    with_items: "{{ parcel_manifest.parcels }}"
    when: item.parcelName.endswith('el7.parcel')

  - name: extract parcels
    unarchive:
      src: /opt/cloudera/parcel-repo/CDH-7.1.3-1.cdh7.1.3.p0.4992530-el7.parcel
      dest: /opt/cloudera/parcels/
      owner: cloudera-scm
      group: cloudera-scm
      mode: '0740'
      remote_src: yes

  - name: symlink the parcel dir
    file:
      src: /opt/cloudera/parcels/CDH-7.1.3-1.cdh7.1.3.p0.4992530
      dest: /opt/cloudera/parcels/CDH
      owner: cloudera-scm
      group: cloudera-scm
      mode: '0740'
      state: link

  - name: create don't delete
    file:
      path: /opt/cloudera/parcels/CDH/.dont_delete
      state: touch
      owner: cloudera-scm
      group: cloudera-scm
      mode: '0740'

  - name: bulk chown
    file:
      path: /opt/cloudera
      state: directory
      recurse: yes
      owner: cloudera-scm
      group: cloudera-scm
      mode: '0740'
